trms/cablecast-public-site

app/components/contact-us/template.hbs
=> Open social links in new tab

app/components/channel-footer/template.hbs, app/components/contact-us/template.hbs, app/controllers/application.js, app/templates/application.hbs
This commit hides the podcasts link in the footer if there are no
podcasts available on the system.
=> Hide Podcast Link if there are no podcasts

app/routes/index.js
This prevents the slide show and gallery from showing shows that are cleared.
=> bugzid: 10125 - Provide location filter to api to exclude cleared shows

app/adapters/application.js, app/router.js, appveyor.yml, config/environment.js, public/fastboot-server.iisnode, public/web.config
This also has some tweaks to make the site work in production as well as some more fastboot work chris and I did pariing
=> Get fastboot deployable in iisnode

app/routes/schedule.js, ember-cli-build.js
Import bootstrap if not in fastboot
=> cc-86-fix-bootstrap-carousel

app/models/channel.js, app/routes/application.js, app/routes/schedule.js
I also removed unused relationships from the channel model.
And the schedule item already had the capability to side load what it
needed so I cleaned up that route's model.
=> cc-82 update to take advantage of channel side loading caps

app/routes/search.js
the channel model is nested and can't be accessed directly
=> cc-96 fix the search

app/components/preview-schedule/template.hbs, app/components/schedule-row/template.hbs, app/styles/colors.scss
Clicking the now plaque, or any other time plaque, will link to the
corresponding event.
=> cc-32 schedule 'plaques' are now links

app/routes/index.js
I restored the filterShow function from master, must've got lost along the
way. It also filters cgExempt shows.
=> cc-129 carousel and galleries display only shows with thumbnails

app/routes/index.js
=> cc-133 use siteName when setting browser's title

app/routes/application.js
when the model hook fires on channel change in the application route we need to reset the page scroll via the reset page scroll mixin
=> CC-143 reset scroll on application route

app/components/show-details/template.hbs
=> CC-159 remove the word on from 'Premiered On'

app/components/channel-stub/component.js, app/components/channel-stub/template.hbs, app/models/public-site.js
fallback to header logo and then to default logo
=> CC-164 add square logo for channel list

app/components/paginated-show-list/component.js, app/components/paginated-show-list/template.hbs, app/components/pagination-control/component.js, app/routes/gallery.js, app/templates/gallery.hbs
The initial issue was a missing set of commoas so the offset was calculated but that exposed issues with the pagination as well
=> CC-523 fix gallery page

app/components/show-details/component.js, app/components/show-details/template.hbs, app/helpers/show-field.js, app/helpers/total-run-time.js, app/models/field-display.js, app/models/public-site.js, app/models/show.js, app/routes/application.js, app/routes/show.js, app/serializers/public-site.js, app/services/site.js, app/styles/app.scss, app/utils/timecode.js
First stab at displaying user defined field displays. More work comming next with different design layouts.
=> CC-760 - Display field displays in show page.

app/components/pdf-viewer/component.js, app/components/pdf-viewer/template.hbs, app/components/show-details/template.hbs, app/components/vod-chapters/template.hbs, app/controllers/show.js, app/models/web-file.js, app/styles/app.scss, app/templates/application.hbs, app/templates/show.hbs, package.json
This brings in `ember-pdf-js` but actually uses a custom component that behaves a bit better for scaling.
This alo applies a bunch of styling tweaks for the show page from Amber.
TODO - drop ember-pdf-js dependency and just rely of mozilla's pdf js directly
=> CC-761 - Show Page Layout Supports Embeded PDFS

app/controllers/show.js, app/models/chapter.js, app/templates/show.hbs
Removed an instance where deleted chapters were displayed.
Removed quickAdded chapters from display.
=> updated chapter display selection

app/templates/search.hbs
Wasn't loading current page/pagesize or total to display pagination in
the search template
=> CC-733 Added missing components to the search template

app/components/show-thumbnail/component.js, app/templates/show.hbs
pre-cursor to allowing custom 'placeholder' thumbnails.
=> CC-1235 Added check to show thumbnail or do nothing

app/components/schedule-row/template.hbs, app/models/vod.js, app/templates/show.hbs
-Make VOD available as soon as one HLS variant is completed.
=> CC-2076 VOD Transcode In Separate Variants

app/controllers/show.js, app/models/field-display.js
=> CC-3208 Agenda Link

app/components/show-thumbnail/component.js, app/controllers/show.js, app/models/field-display.js, app/models/show.js
=> CC-3194 Backport Agenda Link
